### ISSUE TITLE
Single tab restriction rejects single tab 

### ISSUE THREAD

**Issue by mwcz** [GoogleChrome/node-big-rig#4]
I made a timeline recording in Chrome 44.0.2391.0 dev (64-bit).  Bigrig rejected it with "Unable to process trace: Multiple processes (tabs) found." even though there was only a single tab open in Chrome.  There was only one Chrome instance running on this machine.

**Comment by mwcz** [comment]
Chrome 42.0.2311.152 (64-bit) doesn't show the same problem.  Perhaps some feature was spun off into a separate process between 42 and 44 which is tripping the one-tab condition.

**Comment by tyscorp** [comment]
I'm getting this with Chrome 48.0.2552.0 dev-m (64-bit)

**Comment by paullewis** [comment]
Any chance you can put the trace somewhere I can download it and check?

**Comment by mwcz** [comment]
@paullewis sent via email.

**Comment by kdzwinel** [comment]
It turns out that it happens because of some Chrome extensions (in my case it was "[Cookie Inspector](https://chrome.google.com/webstore/detail/cookie-inspector/jgbbilmfbammlbbhmmgaagdkbkepnijn?hl=en)"). My guess is that extensions injecting content scripts mess up the timeline because Chrome creates an "isolated world" inside a tab for them.

**Comment by paullewis** [comment]
Fixed in 916177d.

@kdzwinel is right, it appears to be extensions. This should be fixed in 1.0.5 (published) where background pages will be ignored. You can also add the `--strict` flag if you want Big Rig to throw when it encounters an extension (which you probably will as they skew results!).

**Comment by paullewis** [comment]
Thanks for filing and letting me know!

**Comment by felixzapata** [comment]
hi, I have the same problem. I am trying to parse some files from differents websites and when I run the command (with `strict` option), the console throws: `Unable to process trace: Multiple processes (tabs) found`.

I am using Chrome for Ubuntu.
