### ISSUE TITLE
Problem parsing trace file

### ISSUE THREAD

**Issue by justmarkup** [GoogleChrome/node-big-rig#5]
I have been trying the CLI module today and while the examples from this Repo work just fine any trace file I download from WebPageTest (eg. http://www.webpagetest.org/getgzip.php?test=151109_5S_VYM&file=1_trace.json) throws an error

```
Unable to process trace: Zero processes (tabs) found.
```

After some debugging I found that the files not working look like this:

```
{ traceEvents: 
   [ { args: [Object],
       cat: 'toplevel',
       dur: 71,
       name: 'toplevel',
       ph: 'X',
       pid: 2488,
       tid: 1668,
       ts: 1115677562256 }
    ]
}
```

while the files working look like:

```
[ { pid: 480,
    tid: 622,
    ts: 72977715252,
    ph: 'X',
    cat: 'toplevel',
    name: 'MessagePumpLibevent::OnLibeventNotification',
    args: { fd: 35 },
    dur: 93,
    tdur: 88,
    tts: 133156 }
]
```

As the file starts with `{ traceEvents:`  `events.length` is undefined in the non-working files:
https://github.com/GoogleChrome/node-big-rig/blob/master/lib/third_party/tracing/extras/importer/trace_event_importer.js#L684

I am using Version 1.0.4

**Comment by paullewis** [comment]
Can repro. Will fix now.
