### ISSUE TITLE
Remove --file 

### ISSUE THREAD

**Issue by jillesme** [GoogleChrome/node-big-rig#8]
I have been using bigrig a lot lately. I have created a custom alias (alias br="bigrig --file") because I got tired of typing --file all the time when all I do is pretty print a file.

What is your opinion on dropping the whole --file argument and just assume the first argument is the file path? Most cli tools have that (for example mkdir: it's mkdir [folder], not mkdir --directory [folder])

**Comment by paullewis** [comment]
Picking this up from the other repo, I'll look at it for sure. The knack is making sure we can still pipe data from the BR-runner on the way through too.

**Comment by paullewis** [comment]
Should be fixed in 03dbcc6ba43d2d7738c1fc69f74395bbf44fabb8, published 1.0.9 to npm.
